// <auto-generated />
using System;
using EmployeeWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmployeeWebAPI.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20260906095418_initialize")]
    partial class initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeWebAPI.DBModel.EmployeeDBModel", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("employee_id"));

                    b.Property<int>("authorized_admin")
                        .HasColumnType("integer");

                    b.Property<int>("company_id")
                        .HasColumnType("integer");

                    b.Property<string>("country")
                        .HasColumnType("text");

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("dateOfJoining")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("employee_name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("lastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly?>("lastLoginTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("state")
                        .HasColumnType("text");

                    b.Property<int?>("updated_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("yearsOfExperiance")
                        .HasColumnType("text");

                    b.Property<string>("zipcode")
                        .HasColumnType("text");

                    b.HasKey("employee_id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
